- name: Ensure Docker SDK for Python is installed
  apt:
    name: python3-docker
    state: present

- name: Pull required Docker images
  community.docker.docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    source: pull
  loop: "{{ docker_images }}"
